---
- name: configure master node
  hosts: master
  remote_user: core
  vars_files:
    - vars/node.yaml
    - vars/httpd.yaml

  tasks:
    - name: run coreos installer
      shell: "coreos-installer install --copy-network {{ master_node_blk }} --ignition-url http://{{ bastion }}:{{ httpd_port }}/ocp4/master.ign --insecure-ignition"

    - name: reboot
      reboot:
        reboot_timeout: 1
      ignore_errors: yes

- name: delete master known hosts
  hosts: bastion
  vars_files:
    - vars/node.yaml

  tasks:
    - name: delete master known hosts
      lineinfile:
        path: ~/.ssh/known_hosts
        state: absent
        regexp: "{{ item }}"
      loop: "{{ master }}"
