apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kcb-community-operator-index
  namespace: openshift-marketplace
spec:
  image: registry.buahn.ocp.com:5000/operatorhub/kcb-community-operator-index:v4.10
  sourceType: grpc
